### PR TITLE
Take into account PATHEXT on Windows

### PR DESCRIPTION
**Pull request by alexarchambault**
This env var contains extensions of executable files, separated by ';' (so it looks like ".exe;.bat;…"). It should be taken into account when looking for executables in PATH on Windows.

My hope is that this should help for https://github.com/almond-sh/almond/pull/854.

### CODE REVIEW

**Comment by kiendang** [comment]
Thanks @alexarchambault. Unfortunately I think it takes more than that to make the library works on windows since things like `sys.abiflags` or `sysconfig.get_config_var('LIBPL')` don't exist on windows. I was working briefly on this earlier in #24. Will take a closer look later.

**Comment by alexarchambault** [comment]
@kiendang I might have a bit of time to have look too, if you wish.

**Comment by kiendang** [comment]
Thanks. I used

```
import sys
sys.abiflags
```
to detect if it's "python3.8" or "python3.8m". On windows this does not exist so in the last commit I just remove it for windows

I used

```
import sysconfig
sysconfig.get_config_var(LIBPL)
```

to detect the location of libpython. On windows this is None so I just fall back to `sys.base_prefix/lib`.

The problem now is that still the libpython e.g. "python3.8" is not found on Windows. If you help time could you check for a Python installation on a Windows machine if there is any libpython under `sys.base_prefix/lib`? Whether we have the name wrong or the location wrong or if it exists at all.

**Comment by kiendang** [comment]
@alexarchambault also just invited you as collaborator so you don't need to get approved for CI runs.

**Comment by alexarchambault** [comment]
Cool, thanks!

**Comment by kiendang** [comment]
@alexarchambault looks like this works now. So basically on windows the Python shared lib is located in `sys.base_prefix` and named `python39.dll` (no dot version), at least inside the github action runner anyway. Will cut a release with this fix so we can use in almond-sh/almond#854

**Pull request merged**
